language: rust
before_script: cargo install --force mdbook
script: mdbook build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: book
  on:
    branch: master
